#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RearLeft,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           Right,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Left,          tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		if (vexRT[Btn5U] == true){
			motor[FrontLeft] = 80;
			motor[RearLeft] = 80;
			motor[Right] = 80;
			motor[Left] = 80;
		}
		else if (vexRT[Btn5U] == false) {
			motor[FrontLeft] = 0;
			motor[RearLeft] = 0;
			motor[Right] = 0;
			motor[Left] = 0;
		}
	}
}
