#pragma config(Sensor, in2,    Light,          sensorReflection)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           Shootermotor1, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Shootermotor2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Shootermotor3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Shootermotor4, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Declare variables
int lightVal = 0;
int sonarVal = 0;
int axis3 = 0;
int axis4 = 0;
int speed = 0;

task sensors()
{
	while (true) {
		//Find light sensor and ultrasonic sensor values
		sonarVal = SensorValue[Sonar];
		lightVal = SensorValue[Light];
		//Don't hog CPU
		wait1Msec(25);
	}
}

task joystick()
{
	while (true){
		//Store axis values to variables
		axis3 = vexRT[Ch3];
		axis4 = vexRT[Ch4];
		//Don't hog CPU
		wait1Msec(25);
	}
}

task shooter()
{
	for(;;) {
		/*Motor 1 and 2 are already reversed in port configuration
		motor[Shootermotor1] = floor ((vexRT[Ch2]/127)*80);
		motor[Shootermotor2] = floor ((vexRT[Ch2]/127)*80);
		motor[Shootermotor3] = floor ((vexRT7[Ch2]/127)*80);
		motor[Shootermotor4] = floor ((vexRT[Ch2]/127)*80);*/
		speed = vexRT[Ch2];
		if (speed >= 80) {
			speed = 80;
		}
		//Motor 1 and 2 are already reversed in port configuration
		motor[Shootermotor1] = speed;
		motor[Shootermotor2] = speed;
		motor[Shootermotor3] = speed;
		motor[Shootermotor4] = speed;
	}
}

task main()
{
	startTask(sensors);
	startTask(joystick);
	startTask(shooter);
}
