#pragma config(Sensor, in2,    Light,          sensorReflection)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           RearLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           RearRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           Shootermotor1, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Shootermotor2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Shootermotor3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           Shootermotor4, tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Declare variables
int lightVal = 0;
int sonarVal = 0;
int axis1 = 0;
int axis2 = 0;
int axis3 = 0;
int axis4 = 0;
int speed = 0;

task sensors()
{
	while (true) {
		//Find light sensor and ultrasonic sensor values
		sonarVal = SensorValue[Sonar];
		lightVal = SensorValue[Light];
		//Don't hog CPU
		wait1Msec(25);
	}
}

task joystick()
{
	while (true){
		//Store axis values to variables
		axis1 = vexRT[Ch1];
		axis2 = vexRT[Ch2];
		axis3 = vexRT[Ch3];
		axis4 = vexRT[Ch4];
		//Don't hog CPU
		wait1Msec(25);
	}
}

task shooter()
{
	while(true) {
		//14ft shot
		if (vexRT[Btn8U == true]){
			speed = 80;
		}
		//10ft shot
		else if (vexRT[Btn8R == true]){
			speed = 60;
		}
		//6ft shot
		else if (vexRT[Btn8U == true]){
			speed = 40;
		}
		//Motor 1 and 2 are already reversed in port configuration
		motor[Shootermotor1] = speed;
		motor[Shootermotor2] = speed;
		motor[Shootermotor3] = speed;
		motor[Shootermotor4] = speed;
	}
}

task driving()
{
	//Check the driving code later
	motor[FrontLeft] = axis3 - axis4;
	motor[FrontRight] = axis3 + axis4;
	motor[RearLeft] = axis3 - axis4;
	motor[RearRight] = axis3 + axis4;
	wait1Msec(25);
}

task main()
{
	startTask(sensors);
	startTask(joystick);
	startTask(shooter);
	startTask(driving);
}
